services:
  db:
    image: postgres
    container_name: demo_db
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ecommerce
      - POSTGRES_USER=demo_user
      - POSTGRES_PASSWORD=demo_password
    ports:
      - 5432:5432

  cache:
    image: redis
    container_name: demo_cache
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
  
  meilisearch:
    image: getmeili/meilisearch:v1.12
    container_name: demo_search
    environment:
      MEILI_MASTER_KEY: royce_key
    ports:
      - "7700:7700"
    volumes:
      - search:/data

volumes:
  db:
    driver: local
  cache:
    driver: local
  search:
    driver: local
