services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=medusa_db
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
    ports:
      - 5432:5432

  cache:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
  
  meilisearch:
    image: getmeili/meilisearch:v1.12
    container_name: meilisearch
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9002:9000" # connect on port 9002 from other service like medusajs BE.
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: masoud
      MINIO_ROOT_PASSWORD: Strong#Pass#2022
    command: server --console-address ":9001" /data

volumes:
  db:
    driver: local
  cache:
    driver: local
  minio_storage: {}
