version: "3.9"
services:
  db:
    image: postgres
    container_name: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=medusa_db
      - POSTGRES_USER=yourusername
      - POSTGRES_PASSWORD=yourpassword
    ports:
      - 5432:5432

  cache:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  db:
    driver: local
  cache:
    driver: local
