services:
  db:
    image: postgres
    container_name: royce_db
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=royce_db
      - POSTGRES_USER=royce_user
      - POSTGRES_PASSWORD=royce_password
    ports:
      - 5432:5432

  cache:
    image: redis
    container_name: royce_redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
  
  meilisearch:
    image: getmeili/meilisearch:v1.12
    container_name: royce_meilisearch
    environment:
      MEILI_MASTER_KEY: royce_key
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data

volumes:
  db:
    driver: local
  cache:
    driver: local
