# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  up:
    cmds:
      - docker compose up --build -d
    silent: true
    desc: "Start the Datasources"
  down:
    cmds:
      - docker compose down
    silent: true
    desc: "Stop the Datasources"
  expose:
    cmds:
      - ngrok http 8000
    desc: "Expose the Storefront running on port 8000 to Internet"
